name: 'Continuous Delivery'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: reto-latam-nilton
  REGION: us-central1
  REPOSITORY: latam-repo
  SERVICE: yolo11-api
  IMAGE_NAME: yolo11-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Auth Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      # 2. Configurar Docker para Artifact
      - name: Configure Docker for Artifact
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      # 3. Build imagen Docker
      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest .

      # 4. Push a Artifact
      - name: Push Docker image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest

      # 5. Deploy Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          region: ${{ env.REGION }}
          flags: >
            --allow-unauthenticated
            --max-instances=1
            --min-instances=0